const discogList = [
    {
        year: 2020,
        artist: "Damp",
        link: "https://thisbandisdamp.bandcamp.com/album/damp",
        title: "Damp",
        credit: "Additional Guitar",
    },
    {
        year: 2020,
        artist: "Washer",
        link: "https://okwasher.bandcamp.com/album/bethlehem-steel-washer-split",
        title: "Bethlehem Steel / Washer Split 7\" ",
        credit: "Songwriting, Production, Art, Graphic Design",
    },
    {
        year: 2018,
        artist: "Big Ups",
        link: "https://bigups.bandcamp.com/album/two-parts-together",
        title: "Two Parts Together",
        credit: "Additional Percussion",
    },
    {
        year: 2017,
        artist: "Washer",
        link: "https://okwasher.bandcamp.com/album/all-aboard",
        title: "All Aboard",
        credit: "Songwriting, Production, Art, Graphic Design",
    },
    {
        year: 2017,
        artist: "E.I.S.",
        link: "http://www.explodinginsoundrecords.com/products/591017-exploding-in-sound-live-at-shea-stadium",
        title: "E.I.S. Live @ Shea Stadium",
        credit: "Addl. Graphic Design and performance of 'Beansy' by Washer",
    },
    {
        year: 2016,
        artist: "Washer",
        link: "https://okwasher.bandcamp.com/album/here-comes-washer",
        title: "Here Comes Washer",
        credit: "Songwriting, Production, Art, Graphic Design",
    },
    {
        year: 2015,
        artist: "Washer",
        link: "https://okwasher.bandcamp.com/album/flagland-washer-split-7",
        title: "Flagland / Washer Split 7\"",
        credit: "Songwriting, Production, Graphic Design",
    },
    {
        year: 2014,
        artist: "Washer",
        link: "https://okwasher.bandcamp.com/album/big-ups-washer-split-7",
        title: "Big Ups / Washer Split 7\"",
        credit: "Songwriting, Production, Graphic Design",
    },
    {
        year: 2014,
        artist: "Shakes",
        link: "https://shakesnj.bandcamp.com/album/the-same-7",
        title: "The Same 7\"",
        credit: "Production",
    },
    {
        year: 2014,
        artist: "Washer",
        link: "https://okwasher.bandcamp.com/album/bighead-ep",
        title: 'Bighead EP',
        credit: "Songwriting, Production, Art, Graphic Design",
    },
    {
        year: 2013,
        artist: "Mike Quigley",
        link: "https://boogerspit.bandcamp.com/album/okay-alright",
        title: "okay || alright",
        credit: "Songwriting, Production, Art, Graphic Design",
    },
    {
        year: 2013,
        artist: "clownfacee",
        link: "https://clownfacee.bandcamp.com/album/fear-or-favor",
        title: "Fear or Favor",
        credit: "Songwriting, Recording, Production, Art, Graphic Design",
    },
    {
        year: 2012,
        artist: "Noble Hunter",
        link: "https://noblehunter.bandcamp.com/album/noble-hunter-2",
        title: "Noble Hunter",
        credit: "Guitar, Vocals",
    },
    {
        year: 2012,
        artist: "Incorporated Village of Ghost",
        link: "https://ivog.bandcamp.com/album/fuck-it-im-a-flamethrower",
        title: "Fuck It, I'm A Flamethrower",
        credit: "Recording, Mixing, Production",
    },
    {
        year: 2011,
        artist: "clownfacee",
        link: "https://clownfacee.bandcamp.com/album/winter-ep",
        title: "Winter EP",
        credit: "Songwriting, Recording, Mixing, Production, Art, Graphic Design",
    },
]

export default discogList;